# Generated by Django 3.1.5 on 2021-02-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='informapp',
            new_name='inform',
        ),
    ]
