# Generated by Django 3.1.5 on 2021-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='', upload_to='project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='title2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
